import type { DiscoverySourceConfig } from "./types";

export const DISCOVERY_SOURCES: DiscoverySourceConfig[] = [
  // --- Tier 1: Major Job & Opportunity Platforms ---
  {
    // Facebook Jobs & Events are publicly indexed by search engines.
    // Individual opportunity pages may require a Facebook account to interact with,
    // but the core content (title, description, organization, deadline) is often
    // accessible in the page HTML returned to crawlers. The pipeline's AI extractor
    // processes whatever content is available and rejects incomplete entries using
    // the same quality gate applied to all other sources.
    //
    // Integration strategy: web-search queries via Tavily — identical to LinkedIn,
    // Indeed, and all other Tier 1 sources. No Facebook API credentials required.
    id: "facebook-jobs",
    name: "Facebook Jobs",
    domain: "facebook.com",
    types: ["job"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:facebook.com/jobs software engineer",
      "site:facebook.com/jobs developer",
      "site:facebook.com/jobs frontend developer",
      "site:facebook.com/jobs backend developer",
      "site:facebook.com/jobs remote developer",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "facebook-hackathons",
    name: "Facebook Events (Hackathons)",
    domain: "facebook.com",
    types: ["hackathon"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:facebook.com/events hackathon developer",
      "site:facebook.com/events coding challenge",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "linkedin-jobs",
    name: "LinkedIn Jobs",
    domain: "linkedin.com",
    types: ["job"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:linkedin.com/jobs/view software engineer",
      "site:linkedin.com/jobs/view frontend developer",
      "site:linkedin.com/jobs/view full stack typescript",
      "site:linkedin.com/jobs/view backend developer",
      "site:linkedin.com/jobs/view developer internship",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "indeed",
    name: "Indeed",
    domain: "indeed.com",
    types: ["job"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:indeed.com/viewjob software engineer",
      "site:indeed.com/viewjob frontend developer",
      "site:indeed.com/viewjob junior software developer",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "wellfound",
    name: "Wellfound",
    domain: "wellfound.com",
    types: ["job"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:wellfound.com/jobs software engineer",
      "site:wellfound.com/jobs developer",
      "site:wellfound.com/jobs frontend developer",
      "site:wellfound.com/jobs backend developer",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "greenhouse",
    name: "Greenhouse",
    domain: "boards.greenhouse.io",
    types: ["job"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:boards.greenhouse.io software engineer",
      "site:boards.greenhouse.io frontend",
      "site:boards.greenhouse.io full stack",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "lever",
    name: "Lever",
    domain: "jobs.lever.co",
    types: ["job"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:jobs.lever.co software engineer",
      "site:jobs.lever.co frontend",
      "site:jobs.lever.co backend developer",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "ashby",
    name: "Ashby",
    domain: "jobs.ashbyhq.com",
    types: ["job"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:jobs.ashbyhq.com software engineer",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "ycombinator",
    name: "Y Combinator Jobs",
    domain: "ycombinator.com",
    types: ["job"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:ycombinator.com/jobs software engineer",
      "site:ycombinator.com/jobs developer",
    ],
    refreshIntervalHours: 4,
  },

  // --- Tier 1: Hackathons ---
  {
    id: "devpost",
    name: "Devpost",
    domain: "devpost.com",
    types: ["hackathon"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "both",
    queries: [
      "site:devpost.com hackathon",
      "site:devpost.com AI hackathon",
      "site:devpost.com student hackathon",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "lablab",
    name: "LabLab",
    domain: "lablab.ai",
    types: ["hackathon"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:lablab.ai/event hackathon",
      "site:lablab.ai/event AI hackathon",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "hackerearth",
    name: "HackerEarth",
    domain: "hackerearth.com",
    types: ["hackathon"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:hackerearth.com/challenges/hackathon hackathon",
      "site:hackerearth.com/challenges/hackathon AI",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "kaggle",
    name: "Kaggle",
    domain: "kaggle.com",
    types: ["competition"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:kaggle.com/competitions machine learning",
      "site:kaggle.com/competitions data science",
    ],
    refreshIntervalHours: 4,
  },
  {
    id: "mlh",
    name: "Major League Hacking",
    domain: "mlh.io",
    types: ["hackathon"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:mlh.io/seasons hackathon",
    ],
    refreshIntervalHours: 4,
  },

  // --- Tier 1: Grants & Fellowships ---
  {
    id: "grants-gov",
    name: "Grants.gov",
    domain: "grants.gov",
    types: ["grant"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:grants.gov research grant technology",
      "site:grants.gov innovation funding",
    ],
    refreshIntervalHours: 6,
  },
  {
    id: "techstars",
    name: "Techstars",
    domain: "techstars.com",
    types: ["fellowship"],
    priority: 1,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "site:techstars.com/accelerators",
    ],
    refreshIntervalHours: 6,
  },

  // --- Tier 2: General Sources ---
  {
    id: "generic-jobs",
    name: "Generic Job Boards",
    domain: "",
    types: ["job"],
    priority: 2,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "remote software engineer jobs",
      "junior software developer jobs",
      "frontend developer jobs",
      "backend developer jobs",
      "full stack developer jobs",
      "developer internship",
      "student software engineering internship",
    ],
    refreshIntervalHours: 12,
  },
  {
    id: "generic-hackathons",
    name: "Generic Hackathons",
    domain: "",
    types: ["hackathon"],
    priority: 2,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "upcoming hackathon 2026",
      "open hackathon 2026",
      "AI hackathon 2026",
      "developer hackathon 2026",
      "student hackathon 2026",
    ],
    refreshIntervalHours: 12,
  },
  {
    id: "generic-grants",
    name: "Generic Grants",
    domain: "",
    types: ["grant"],
    priority: 2,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "technology startup grants 2026",
      "developer grants 2026",
      "innovation grants 2026",
      "startup funding opportunities 2026",
    ],
    refreshIntervalHours: 12,
  },
  {
    id: "generic-fellowships",
    name: "Generic Fellowships",
    domain: "",
    types: ["fellowship"],
    priority: 2,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "founder fellowship software technology 2026",
    ],
    refreshIntervalHours: 12,
  },

  // --- Tier 3: Broad Web Discovery ---
  {
    id: "broad-discovery",
    name: "Broad Web Discovery",
    domain: "",
    types: ["job", "grant", "hackathon", "fellowship", "competition"],
    priority: 3,
    enabled: true,
    discoveryStrategy: "search",
    queries: [
      "latest opportunities for developers 2026",
    ],
    refreshIntervalHours: 24,
  }
];
